<<<<<<< HEAD
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

=======
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";

// Initialize the Geist font
>>>>>>> b778bd4 (Main,Login,Register Page)
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
export const metadata = {
  title: "Your Marketplace",
  description: "ซื้อขายสินค้าออนไลน์",
>>>>>>> b778bd4 (Main,Login,Register Page)
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
=======
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
>>>>>>> b778bd4 (Main,Login,Register Page)
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
